version: '3.8'
services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    environment:
      ORACLE_PASSWORD: teste2
      APP_USER: WEBAPI_TESTE1
      APP_USER_PASSWORD: teste2
    ports:
      - "1522:1521"  # Porta externa 1522 → interna 1521 (evita conflito com Oracle local)
    volumes:
      - oracle-data:/opt/oracle/oradata

  backend:
    build:
      context: ./Backend/WebAPI_EmprestimoConsignado
    container_name: emprestimo-backend
    environment:
      - DefaultConnection_EmprestimoConsignado=User Id=WEBAPI_TESTE1;Password=teste2;Data Source=oracle-db:1521/XEPDB1
    ports:
      - "8080:8080"
    depends_on:
      - oracle-db

  frontend:
    build:
      context: ./Frontend
    container_name: emprestimo-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  oracle-data:
