DECLARE
V_COUNT INTEGER;
BEGIN
SELECT COUNT(TABLE_NAME) INTO V_COUNT from USER_TABLES where TABLE_NAME = '__EFMigrationsHistory';
IF V_COUNT = 0 THEN
Begin
BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"__EFMigrationsHistory" (
    "MigrationId" NVARCHAR2(150) NOT NULL,
    "ProductVersion" NVARCHAR2(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
)';
END;

End;

END IF;
EXCEPTION
WHEN OTHERS THEN
    IF(SQLCODE != -942)THEN
        RAISE;
    END IF;
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Clientes" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "Nome" NVARCHAR2(2000) NOT NULL,
    "Sobrenome" NVARCHAR2(2000) NOT NULL,
    "CPF" NVARCHAR2(2000) NOT NULL,
    "DataDeCriacao" TIMESTAMP(7) NOT NULL,
    "DataDeAlteracao" TIMESTAMP(7) NOT NULL,
    CONSTRAINT "PK_Clientes" PRIMARY KEY ("Id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Emprestimos" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "ClienteId" NUMBER(10) NOT NULL,
    "Valor" DECIMAL(18, 2) NOT NULL,
    "Juros" DECIMAL(18, 2) NOT NULL,
    "TipoEmprestimo" NUMBER(10) NOT NULL,
    "Status" NUMBER(10) NOT NULL,
    "DataDeCriacao" TIMESTAMP(7) NOT NULL,
    "DataDeAlteracao" TIMESTAMP(7) NOT NULL,
    CONSTRAINT "PK_Emprestimos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Emprestimos_Clientes_ClienteId" FOREIGN KEY ("ClienteId") REFERENCES "Clientes" ("Id") ON DELETE CASCADE
)';
END;
/

CREATE INDEX "IX_Emprestimos_ClienteId" ON "Emprestimos" ("ClienteId")
/

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20250210144339_first-migration', N'9.0.4')
/

declare
   l_nullable user_tab_columns.nullable % type;
begin 
   select nullable into l_nullable 
   from user_tab_columns 
  where table_name = 'Emprestimos' 
  and column_name = 'Valor' 
;
   if l_nullable = 'N' then 
        EXECUTE IMMEDIATE 'ALTER TABLE "Emprestimos" MODIFY "Valor"  ';
 else 
        EXECUTE IMMEDIATE 'ALTER TABLE "Emprestimos" MODIFY "Valor"  NOT NULL';
 end if;
end;
/

declare
   l_nullable user_tab_columns.nullable % type;
begin 
   select nullable into l_nullable 
   from user_tab_columns 
  where table_name = 'Emprestimos' 
  and column_name = 'Juros' 
;
   if l_nullable = 'N' then 
        EXECUTE IMMEDIATE 'ALTER TABLE "Emprestimos" MODIFY "Juros"  ';
 else 
        EXECUTE IMMEDIATE 'ALTER TABLE "Emprestimos" MODIFY "Juros"  NOT NULL';
 end if;
end;
/

ALTER TABLE "Clientes" ADD "Ativo" NUMBER(1) DEFAULT 0 NOT NULL
/

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20250210205913_second-migration', N'9.0.4')
/

declare
   l_nullable user_tab_columns.nullable % type;
begin 
   select nullable into l_nullable 
   from user_tab_columns 
  where table_name = 'Emprestimos' 
  and column_name = 'Valor' 
;
   if l_nullable = 'N' then 
        EXECUTE IMMEDIATE 'ALTER TABLE "Emprestimos" MODIFY "Valor"  DEFAULT 1.0 ';
 else 
        EXECUTE IMMEDIATE 'ALTER TABLE "Emprestimos" MODIFY "Valor"  DEFAULT 1.0 NOT NULL';
 end if;
end;
/

declare
   l_nullable user_tab_columns.nullable % type;
begin 
   select nullable into l_nullable 
   from user_tab_columns 
  where table_name = 'Emprestimos' 
  and column_name = 'Juros' 
;
   if l_nullable = 'N' then 
        EXECUTE IMMEDIATE 'ALTER TABLE "Emprestimos" MODIFY "Juros"  ';
 else 
        EXECUTE IMMEDIATE 'ALTER TABLE "Emprestimos" MODIFY "Juros"  NOT NULL';
 end if;
end;
/

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20250210213623_AdicionaAtivoComoTrue', N'9.0.4')
/

declare
   l_nullable user_tab_columns.nullable % type;
begin 
   select nullable into l_nullable 
   from user_tab_columns 
  where table_name = 'Emprestimos' 
  and column_name = 'Valor' 
;
   if l_nullable = 'N' then 
        EXECUTE IMMEDIATE 'ALTER TABLE "Emprestimos" MODIFY "Valor"  ';
 else 
        EXECUTE IMMEDIATE 'ALTER TABLE "Emprestimos" MODIFY "Valor"  NOT NULL';
 end if;
end;
/

declare
   l_nullable user_tab_columns.nullable % type;
begin 
   select nullable into l_nullable 
   from user_tab_columns 
  where table_name = 'Emprestimos' 
  and column_name = 'Juros' 
;
   if l_nullable = 'N' then 
        EXECUTE IMMEDIATE 'ALTER TABLE "Emprestimos" MODIFY "Juros"  ';
 else 
        EXECUTE IMMEDIATE 'ALTER TABLE "Emprestimos" MODIFY "Juros"  NOT NULL';
 end if;
end;
/

declare
   l_nullable user_tab_columns.nullable % type;
begin 
   select nullable into l_nullable 
   from user_tab_columns 
  where table_name = 'Clientes' 
  and column_name = 'Ativo' 
;
   if l_nullable = 'N' then 
        EXECUTE IMMEDIATE 'ALTER TABLE "Clientes" MODIFY "Ativo" NUMBER(1) ';
 else 
        EXECUTE IMMEDIATE 'ALTER TABLE "Clientes" MODIFY "Ativo" NUMBER(1) NOT NULL';
 end if;
end;
/

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20250210215858_CorrigeBooleanoAtivo', N'9.0.4')
/

ALTER TABLE "Clientes" RENAME COLUMN "Sobrenome" TO "Email"
/

declare
   l_nullable user_tab_columns.nullable % type;
begin 
   select nullable into l_nullable 
   from user_tab_columns 
  where table_name = 'Emprestimos' 
  and column_name = 'Valor' 
;
   if l_nullable = 'N' then 
        EXECUTE IMMEDIATE 'ALTER TABLE "Emprestimos" MODIFY "Valor"  NULL';
 else 
        EXECUTE IMMEDIATE 'ALTER TABLE "Emprestimos" MODIFY "Valor" ';
 end if;
end;
/

declare
   l_nullable user_tab_columns.nullable % type;
begin 
   select nullable into l_nullable 
   from user_tab_columns 
  where table_name = 'Emprestimos' 
  and column_name = 'TipoEmprestimo' 
;
   if l_nullable = 'N' then 
        EXECUTE IMMEDIATE 'ALTER TABLE "Emprestimos" MODIFY "TipoEmprestimo"  NULL';
 else 
        EXECUTE IMMEDIATE 'ALTER TABLE "Emprestimos" MODIFY "TipoEmprestimo" ';
 end if;
end;
/

declare
   l_nullable user_tab_columns.nullable % type;
begin 
   select nullable into l_nullable 
   from user_tab_columns 
  where table_name = 'Emprestimos' 
  and column_name = 'Status' 
;
   if l_nullable = 'N' then 
        EXECUTE IMMEDIATE 'ALTER TABLE "Emprestimos" MODIFY "Status"  NULL';
 else 
        EXECUTE IMMEDIATE 'ALTER TABLE "Emprestimos" MODIFY "Status" ';
 end if;
end;
/

declare
   l_nullable user_tab_columns.nullable % type;
begin 
   select nullable into l_nullable 
   from user_tab_columns 
  where table_name = 'Emprestimos' 
  and column_name = 'Juros' 
;
   if l_nullable = 'N' then 
        EXECUTE IMMEDIATE 'ALTER TABLE "Emprestimos" MODIFY "Juros"  NULL';
 else 
        EXECUTE IMMEDIATE 'ALTER TABLE "Emprestimos" MODIFY "Juros" ';
 end if;
end;
/

ALTER TABLE "Clientes" ADD "DataContratacao" TIMESTAMP(7) DEFAULT TO_TIMESTAMP('0001-01-01 00:00:00.0000000', 'YYYY-MM-DD HH24:MI:SS.FF') NOT NULL
/

ALTER TABLE "Clientes" ADD "QtdParcelas" NUMBER(10) DEFAULT 0 NOT NULL
/

ALTER TABLE "Clientes" ADD "StatusEmprestimo" NUMBER(10) DEFAULT 0 NOT NULL
/

ALTER TABLE "Clientes" ADD "TipoEmprestimo" NUMBER(10) DEFAULT 0 NOT NULL
/

ALTER TABLE "Clientes" ADD "ValorEmprestimo" DECIMAL(18,2) DEFAULT 0.0 NOT NULL
/

ALTER TABLE "Clientes" ADD "ValorParcela" DECIMAL(18,2) DEFAULT 0.0 NOT NULL
/

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20250214212401_4th', N'9.0.4')
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"Usuarios" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "Nome" NVARCHAR2(250) NOT NULL,
    "Email" NVARCHAR2(250) NOT NULL,
    "PasswordHash" RAW(512) NOT NULL,
    "PasswordSalt" RAW(512) NOT NULL,
    CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id")
)';
END;
/

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20250321143834_usuarioTabela', N'9.0.4')
/

ALTER TABLE "Usuarios" ADD "Usuario" NVARCHAR2(2000) NOT NULL
/

ALTER TABLE "Usuarios" ADD "Cargo" NUMBER(10) DEFAULT 0 NOT NULL
/

ALTER TABLE "Usuarios" ADD "SenhaHash" RAW(2000) DEFAULT HEXTORAW('') NOT NULL
/

ALTER TABLE "Usuarios" ADD "SenhaSalt" RAW(2000) DEFAULT HEXTORAW('') NOT NULL
/

ALTER TABLE "Usuarios" ADD "TokenDataCriacao" TIMESTAMP(7) DEFAULT (CURRENT_TIMESTAMP) NOT NULL
/

ALTER TABLE "Usuarios" DROP COLUMN "Nome"
/

ALTER TABLE "Usuarios" DROP COLUMN "PasswordHash"
/

ALTER TABLE "Usuarios" DROP COLUMN "PasswordSalt"
/

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20250327165745_UsuarioModel', N'9.0.4')
/

